### ISSUE TITLE
Is there a reason why the tracker interface in actions is not identical to the core or even uses the same class?

### ISSUE THREAD

**Issue by deW1** [RasaHQ/rasa_core_sdk#23]
How does one use `as_dialogue`, `export_stories`, `export_stories_to_file`?

**Comment by akelad** [comment]
Because we don't want there to be too many interdependencies basically. The `rasa_core_sdk` only has the attributes of the tracker that are necessary for the action execution side. 
The rest of your questions are related to rasa core right? You won't need those here, as those are relevant to stories, rather than actions specifically.
Since this is more of a usage question, I'm going to close this issue. Please ask any more questions you have in the [forum](https://forum.rasa.com)
